<?php

/**
 * @file
 * Person Schema module file.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function person_schema_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  if ($node->bundle() == 'person') {
    // Add JavaScript for hide/show functionality.
    $form['#attached']['library'][] = 'person_schema/name_toggle';

    // Add submit handler to set name fields to 'Unknown' if name not known.
    $form['#submit'][] = 'person_schema_node_form_submit';
  }
}

/**
 * Submit handler for person node form.
 */
function person_schema_node_form_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  if ($node->bundle() == 'person') {
    $name_known = $form_state->getValue('field_name_known');

    if (empty($name_known[0]['value'])) {
      // Name not known, set to 'Unknown'.
      $form_state->setValue('field_given_name', [['value' => 'Unknown']]);
      $form_state->setValue('field_family_name', [['value' => 'Unknown']]);
    }
  }
}